# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

development:
  adapter: postgresql
  host: localhost
  database: railsblog_dev
  username: postgres
  password: admin
  pool: 5
  timeout: 5000